// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_tokens.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAccessTokens = `-- name: CountAccessTokens :one
SELECT COUNT(*) FROM access_tokens
WHERE
    ($1::uuid IS NULL OR client_id = $1) AND
    ($2::uuid IS NULL OR user_id = $2) AND
    ($3::boolean IS NULL OR is_revoked = $3)
`

type CountAccessTokensParams struct {
	Column1 uuid.UUID
	Column2 uuid.UUID
	Column3 bool
}

func (q *Queries) CountAccessTokens(ctx context.Context, arg CountAccessTokensParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAccessTokens, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO access_tokens (
    token_hash,
    client_id,
    user_id,
    scope,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, token_hash, client_id, user_id, scope, expires_at, is_revoked, created_at
`

type CreateAccessTokenParams struct {
	TokenHash string
	ClientID  *uuid.UUID
	UserID    uuid.UUID
	Scope     *string
	ExpiresAt time.Time
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (AccessToken, error) {
	row := q.db.QueryRow(ctx, createAccessToken,
		arg.TokenHash,
		arg.ClientID,
		arg.UserID,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAccessTokens = `-- name: DeleteExpiredAccessTokens :exec
DELETE FROM access_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredAccessTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAccessTokens)
	return err
}

const getAccessToken = `-- name: GetAccessToken :one
SELECT id, token_hash, client_id, user_id, scope, expires_at, is_revoked, created_at FROM access_tokens
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetAccessToken(ctx context.Context, tokenHash string) (AccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessToken, tokenHash)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const getAccessTokenByID = `-- name: GetAccessTokenByID :one
SELECT id, token_hash, client_id, user_id, scope, expires_at, is_revoked, created_at FROM access_tokens
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccessTokenByID(ctx context.Context, id uuid.UUID) (AccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByID, id)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.Scope,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const listAccessTokens = `-- name: ListAccessTokens :many
SELECT id, token_hash, client_id, user_id, scope, expires_at, is_revoked, created_at FROM access_tokens
WHERE
    ($1::uuid IS NULL OR client_id = $1) AND
    ($2::uuid IS NULL OR user_id = $2) AND
    ($3::boolean IS NULL OR is_revoked = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAccessTokensParams struct {
	Column1 uuid.UUID
	Column2 uuid.UUID
	Column3 bool
	Limit   int32
	Offset  int32
}

func (q *Queries) ListAccessTokens(ctx context.Context, arg ListAccessTokensParams) ([]AccessToken, error) {
	rows, err := q.db.Query(ctx, listAccessTokens,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccessToken
	for rows.Next() {
		var i AccessToken
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.ClientID,
			&i.UserID,
			&i.Scope,
			&i.ExpiresAt,
			&i.IsRevoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAccessToken = `-- name: RevokeAccessToken :exec
UPDATE access_tokens
SET is_revoked = true
WHERE id = $1
`

func (q *Queries) RevokeAccessToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAccessToken, id)
	return err
}

const revokeAccessTokensByClient = `-- name: RevokeAccessTokensByClient :exec
UPDATE access_tokens
SET is_revoked = true
WHERE client_id = $1
`

func (q *Queries) RevokeAccessTokensByClient(ctx context.Context, clientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAccessTokensByClient, clientID)
	return err
}

const revokeAccessTokensByUser = `-- name: RevokeAccessTokensByUser :exec
UPDATE access_tokens
SET is_revoked = true
WHERE user_id = $1
`

func (q *Queries) RevokeAccessTokensByUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAccessTokensByUser, userID)
	return err
}
