// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countAuditLogEntries = `-- name: CountAuditLogEntries :one
SELECT COUNT(*) FROM audit_log
WHERE
    ($1::text IS NULL OR event_type = $1) AND
    ($2::uuid IS NULL OR user_id = $2) AND
    ($3::uuid IS NULL OR client_id = $3)
`

type CountAuditLogEntriesParams struct {
	Column1 string
	Column2 uuid.UUID
	Column3 uuid.UUID
}

func (q *Queries) CountAuditLogEntries(ctx context.Context, arg CountAuditLogEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogEntries, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLogEntry = `-- name: CreateAuditLogEntry :one
INSERT INTO audit_log (
    event_type,
    user_id,
    client_id,
    actor_id,
    ip_address,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id
`

type CreateAuditLogEntryParams struct {
	EventType string
	UserID    uuid.UUID
	ClientID  uuid.UUID
	ActorID   uuid.UUID
	IpAddress *string
	Metadata  []byte
}

func (q *Queries) CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAuditLogEntry,
		arg.EventType,
		arg.UserID,
		arg.ClientID,
		arg.ActorID,
		arg.IpAddress,
		arg.Metadata,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAuditLogEntries = `-- name: ListAuditLogEntries :many
SELECT id, event_type, user_id, client_id, actor_id, ip_address, metadata, created_at FROM audit_log
WHERE
    ($1::text IS NULL OR event_type = $1) AND
    ($2::uuid IS NULL OR user_id = $2) AND
    ($3::uuid IS NULL OR client_id = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditLogEntriesParams struct {
	Column1 string
	Column2 uuid.UUID
	Column3 uuid.UUID
	Limit   int32
	Offset  int32
}

func (q *Queries) ListAuditLogEntries(ctx context.Context, arg ListAuditLogEntriesParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogEntries,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.UserID,
			&i.ClientID,
			&i.ActorID,
			&i.IpAddress,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
