// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authorization_codes.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAuthorizationCodes = `-- name: CountAuthorizationCodes :one
SELECT COUNT(*) FROM authorization_codes
WHERE
    ($1::uuid IS NULL OR client_id = $1) AND
    ($2::uuid IS NULL OR user_id = $2) AND
    ($3::boolean IS NULL OR is_revoked = $3)
`

type CountAuthorizationCodesParams struct {
	Column1 uuid.UUID
	Column2 uuid.UUID
	Column3 bool
}

func (q *Queries) CountAuthorizationCodes(ctx context.Context, arg CountAuthorizationCodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthorizationCodes, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthorizationCode = `-- name: CreateAuthorizationCode :one
INSERT INTO authorization_codes (
    code,
    client_id,
    user_id,
    provider_id,
    redirect_uri,
    scope,
    state,
    code_challenge,
    code_challenge_method,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, code, client_id, user_id, provider_id, redirect_uri, scope, state, code_challenge, code_challenge_method, expires_at, used_at, is_revoked, created_at
`

type CreateAuthorizationCodeParams struct {
	Code                string
	ClientID            uuid.UUID
	UserID              uuid.UUID
	ProviderID          uuid.UUID
	RedirectUri         string
	Scope               *string
	State               *string
	CodeChallenge       *string
	CodeChallengeMethod *string
	ExpiresAt           time.Time
}

func (q *Queries) CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, createAuthorizationCode,
		arg.Code,
		arg.ClientID,
		arg.UserID,
		arg.ProviderID,
		arg.RedirectUri,
		arg.Scope,
		arg.State,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ClientID,
		&i.UserID,
		&i.ProviderID,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredAuthorizationCodes = `-- name: DeleteExpiredAuthorizationCodes :exec
DELETE FROM authorization_codes
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredAuthorizationCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthorizationCodes)
	return err
}

const getAuthorizationCode = `-- name: GetAuthorizationCode :one
SELECT id, code, client_id, user_id, provider_id, redirect_uri, scope, state, code_challenge, code_challenge_method, expires_at, used_at, is_revoked, created_at FROM authorization_codes
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetAuthorizationCode(ctx context.Context, code string) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCode, code)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ClientID,
		&i.UserID,
		&i.ProviderID,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const getAuthorizationCodeByID = `-- name: GetAuthorizationCodeByID :one
SELECT id, code, client_id, user_id, provider_id, redirect_uri, scope, state, code_challenge, code_challenge_method, expires_at, used_at, is_revoked, created_at FROM authorization_codes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthorizationCodeByID(ctx context.Context, id uuid.UUID) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getAuthorizationCodeByID, id)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ClientID,
		&i.UserID,
		&i.ProviderID,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthorizationCodes = `-- name: ListAuthorizationCodes :many
SELECT id, code, client_id, user_id, provider_id, redirect_uri, scope, state, code_challenge, code_challenge_method, expires_at, used_at, is_revoked, created_at FROM authorization_codes
WHERE
    ($1::uuid IS NULL OR client_id = $1) AND
    ($2::uuid IS NULL OR user_id = $2) AND
    ($3::boolean IS NULL OR is_revoked = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuthorizationCodesParams struct {
	Column1 uuid.UUID
	Column2 uuid.UUID
	Column3 bool
	Limit   int32
	Offset  int32
}

func (q *Queries) ListAuthorizationCodes(ctx context.Context, arg ListAuthorizationCodesParams) ([]AuthorizationCode, error) {
	rows, err := q.db.Query(ctx, listAuthorizationCodes,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthorizationCode
	for rows.Next() {
		var i AuthorizationCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ClientID,
			&i.UserID,
			&i.ProviderID,
			&i.RedirectUri,
			&i.Scope,
			&i.State,
			&i.CodeChallenge,
			&i.CodeChallengeMethod,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.IsRevoked,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuthorizationCodeUsed = `-- name: MarkAuthorizationCodeUsed :one
UPDATE authorization_codes
SET used_at = now()
WHERE id = $1
RETURNING id, code, client_id, user_id, provider_id, redirect_uri, scope, state, code_challenge, code_challenge_method, expires_at, used_at, is_revoked, created_at
`

func (q *Queries) MarkAuthorizationCodeUsed(ctx context.Context, id uuid.UUID) (AuthorizationCode, error) {
	row := q.db.QueryRow(ctx, markAuthorizationCodeUsed, id)
	var i AuthorizationCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ClientID,
		&i.UserID,
		&i.ProviderID,
		&i.RedirectUri,
		&i.Scope,
		&i.State,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.IsRevoked,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAuthorizationCode = `-- name: RevokeAuthorizationCode :exec
UPDATE authorization_codes
SET is_revoked = true
WHERE id = $1
`

func (q *Queries) RevokeAuthorizationCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAuthorizationCode, id)
	return err
}

const revokeAuthorizationCodeByCode = `-- name: RevokeAuthorizationCodeByCode :exec
UPDATE authorization_codes
SET is_revoked = true
WHERE code = $1
`

func (q *Queries) RevokeAuthorizationCodeByCode(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, revokeAuthorizationCodeByCode, code)
	return err
}
