// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countClients = `-- name: CountClients :one
SELECT COUNT(*) FROM clients
WHERE
    ($1::boolean IS NULL OR is_active = $1)
`

func (q *Queries) CountClients(ctx context.Context, dollar_1 bool) (int64, error) {
	row := q.db.QueryRow(ctx, countClients, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    name,
    description,
    client_secret_hash,
    redirect_uris,
    grant_types,
    is_active,
    created_by,
    is_confidential,
    allow_refresh_tokens
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, name, description, client_secret_hash, redirect_uris, grant_types, is_active, created_by, created_at, updated_at, is_confidential, allow_refresh_tokens
`

type CreateClientParams struct {
	Name               string
	Description        *string
	ClientSecretHash   string
	RedirectUris       []string
	GrantTypes         []string
	IsActive           *bool
	CreatedBy          uuid.UUID
	IsConfidential     bool
	AllowRefreshTokens bool
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.Name,
		arg.Description,
		arg.ClientSecretHash,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.IsActive,
		arg.CreatedBy,
		arg.IsConfidential,
		arg.AllowRefreshTokens,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsConfidential,
		&i.AllowRefreshTokens,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
UPDATE clients
SET is_active = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClient = `-- name: GetClient :one
SELECT id, name, description, client_secret_hash, redirect_uris, grant_types, is_active, created_by, created_at, updated_at, is_confidential, allow_refresh_tokens FROM clients
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetClient(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsConfidential,
		&i.AllowRefreshTokens,
	)
	return i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, name, description, client_secret_hash, redirect_uris, grant_types, is_active, created_by, created_at, updated_at, is_confidential, allow_refresh_tokens FROM clients
WHERE id = $1 AND is_active = true LIMIT 1
`

func (q *Queries) GetClientByID(ctx context.Context, id uuid.UUID) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsConfidential,
		&i.AllowRefreshTokens,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, name, description, client_secret_hash, redirect_uris, grant_types, is_active, created_by, created_at, updated_at, is_confidential, allow_refresh_tokens FROM clients
WHERE
    ($1::boolean IS NULL OR is_active = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListClientsParams struct {
	Column1 bool
	Limit   int32
	Offset  int32
}

func (q *Queries) ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listClients, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ClientSecretHash,
			&i.RedirectUris,
			&i.GrantTypes,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsConfidential,
			&i.AllowRefreshTokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const regenerateClientSecret = `-- name: RegenerateClientSecret :one
UPDATE clients
SET
    client_secret_hash = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, client_secret_hash, redirect_uris, grant_types, is_active, created_by, created_at, updated_at, is_confidential, allow_refresh_tokens
`

type RegenerateClientSecretParams struct {
	ID               uuid.UUID
	ClientSecretHash string
}

func (q *Queries) RegenerateClientSecret(ctx context.Context, arg RegenerateClientSecretParams) (Client, error) {
	row := q.db.QueryRow(ctx, regenerateClientSecret, arg.ID, arg.ClientSecretHash)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsConfidential,
		&i.AllowRefreshTokens,
	)
	return i, err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET
    name = $2,
    description = $3,
    redirect_uris = $4,
    grant_types = $5,
    is_confidential = $6,
    allow_refresh_tokens = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, name, description, client_secret_hash, redirect_uris, grant_types, is_active, created_by, created_at, updated_at, is_confidential, allow_refresh_tokens
`

type UpdateClientParams struct {
	ID                 uuid.UUID
	Name               string
	Description        *string
	RedirectUris       []string
	GrantTypes         []string
	IsConfidential     bool
	AllowRefreshTokens bool
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.IsConfidential,
		arg.AllowRefreshTokens,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ClientSecretHash,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsConfidential,
		&i.AllowRefreshTokens,
	)
	return i, err
}
