// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	models "github.com/SamuelWang/goauth-server/internal/models"
	"github.com/google/uuid"
)

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type User struct {
	ID            uuid.UUID
	Email         string
	EmailVerified bool
	FirstName     *string
	LastName      *string
	IsActive      bool
	Locale        string
	Provider      *string
	ProviderID    *string
	ProviderData  *models.OAuthProviderData
	LastLoginAt   time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
