// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_providers.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createOAuthProvider = `-- name: CreateOAuthProvider :one
INSERT INTO oauth_providers (
    client_id, name, display_name, provider_client_id, provider_client_secret,
    auth_url, token_url, user_info_url, scopes, is_enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, client_id, name, display_name, provider_client_id, provider_client_secret, auth_url, token_url, user_info_url, scopes, is_enabled, created_at, updated_at
`

type CreateOAuthProviderParams struct {
	ClientID             uuid.UUID
	Name                 string
	DisplayName          string
	ProviderClientID     string
	ProviderClientSecret string
	AuthUrl              string
	TokenUrl             string
	UserInfoUrl          string
	Scopes               []string
	IsEnabled            *bool
}

func (q *Queries) CreateOAuthProvider(ctx context.Context, arg CreateOAuthProviderParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, createOAuthProvider,
		arg.ClientID,
		arg.Name,
		arg.DisplayName,
		arg.ProviderClientID,
		arg.ProviderClientSecret,
		arg.AuthUrl,
		arg.TokenUrl,
		arg.UserInfoUrl,
		arg.Scopes,
		arg.IsEnabled,
	)
	var i OauthProvider
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.DisplayName,
		&i.ProviderClientID,
		&i.ProviderClientSecret,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.UserInfoUrl,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthProvider = `-- name: DeleteOAuthProvider :exec
DELETE FROM oauth_providers
WHERE id = $1
`

func (q *Queries) DeleteOAuthProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOAuthProvider, id)
	return err
}

const disableOAuthProvider = `-- name: DisableOAuthProvider :exec
UPDATE oauth_providers
SET is_enabled = false, updated_at = now()
WHERE id = $1
`

func (q *Queries) DisableOAuthProvider(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableOAuthProvider, id)
	return err
}

const getOAuthProvider = `-- name: GetOAuthProvider :one
SELECT id, client_id, name, display_name, provider_client_id, provider_client_secret, auth_url, token_url, user_info_url, scopes, is_enabled, created_at, updated_at FROM oauth_providers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOAuthProvider(ctx context.Context, id uuid.UUID) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, getOAuthProvider, id)
	var i OauthProvider
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.DisplayName,
		&i.ProviderClientID,
		&i.ProviderClientSecret,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.UserInfoUrl,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOAuthProviderByClientAndName = `-- name: GetOAuthProviderByClientAndName :one
SELECT id, client_id, name, display_name, provider_client_id, provider_client_secret, auth_url, token_url, user_info_url, scopes, is_enabled, created_at, updated_at FROM oauth_providers
WHERE client_id = $1 AND name = $2 LIMIT 1
`

type GetOAuthProviderByClientAndNameParams struct {
	ClientID uuid.UUID
	Name     string
}

func (q *Queries) GetOAuthProviderByClientAndName(ctx context.Context, arg GetOAuthProviderByClientAndNameParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, getOAuthProviderByClientAndName, arg.ClientID, arg.Name)
	var i OauthProvider
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.DisplayName,
		&i.ProviderClientID,
		&i.ProviderClientSecret,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.UserInfoUrl,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledOAuthProvidersByClient = `-- name: ListEnabledOAuthProvidersByClient :many
SELECT id, client_id, name, display_name, provider_client_id, provider_client_secret, auth_url, token_url, user_info_url, scopes, is_enabled, created_at, updated_at FROM oauth_providers
WHERE client_id = $1 AND is_enabled = true
ORDER BY display_name
`

func (q *Queries) ListEnabledOAuthProvidersByClient(ctx context.Context, clientID uuid.UUID) ([]OauthProvider, error) {
	rows, err := q.db.Query(ctx, listEnabledOAuthProvidersByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthProvider
	for rows.Next() {
		var i OauthProvider
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.DisplayName,
			&i.ProviderClientID,
			&i.ProviderClientSecret,
			&i.AuthUrl,
			&i.TokenUrl,
			&i.UserInfoUrl,
			&i.Scopes,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOAuthProvidersByClient = `-- name: ListOAuthProvidersByClient :many
SELECT id, client_id, name, display_name, provider_client_id, provider_client_secret, auth_url, token_url, user_info_url, scopes, is_enabled, created_at, updated_at FROM oauth_providers
WHERE client_id = $1
ORDER BY display_name
`

func (q *Queries) ListOAuthProvidersByClient(ctx context.Context, clientID uuid.UUID) ([]OauthProvider, error) {
	rows, err := q.db.Query(ctx, listOAuthProvidersByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthProvider
	for rows.Next() {
		var i OauthProvider
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Name,
			&i.DisplayName,
			&i.ProviderClientID,
			&i.ProviderClientSecret,
			&i.AuthUrl,
			&i.TokenUrl,
			&i.UserInfoUrl,
			&i.Scopes,
			&i.IsEnabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOAuthProvider = `-- name: UpdateOAuthProvider :one
UPDATE oauth_providers
SET display_name = $2,
    provider_client_id = $3,
    provider_client_secret = $4,
    auth_url = $5,
    token_url = $6,
    user_info_url = $7,
    scopes = $8,
    is_enabled = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, client_id, name, display_name, provider_client_id, provider_client_secret, auth_url, token_url, user_info_url, scopes, is_enabled, created_at, updated_at
`

type UpdateOAuthProviderParams struct {
	ID                   uuid.UUID
	DisplayName          string
	ProviderClientID     string
	ProviderClientSecret string
	AuthUrl              string
	TokenUrl             string
	UserInfoUrl          string
	Scopes               []string
	IsEnabled            *bool
}

func (q *Queries) UpdateOAuthProvider(ctx context.Context, arg UpdateOAuthProviderParams) (OauthProvider, error) {
	row := q.db.QueryRow(ctx, updateOAuthProvider,
		arg.ID,
		arg.DisplayName,
		arg.ProviderClientID,
		arg.ProviderClientSecret,
		arg.AuthUrl,
		arg.TokenUrl,
		arg.UserInfoUrl,
		arg.Scopes,
		arg.IsEnabled,
	)
	var i OauthProvider
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Name,
		&i.DisplayName,
		&i.ProviderClientID,
		&i.ProviderClientSecret,
		&i.AuthUrl,
		&i.TokenUrl,
		&i.UserInfoUrl,
		&i.Scopes,
		&i.IsEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
