// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRefreshTokensByUser = `-- name: CountRefreshTokensByUser :one
SELECT COUNT(*) FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) CountRefreshTokensByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRefreshTokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (
    token_hash,
    token_family_id,
    client_id,
    user_id,
    access_token_id,
    previous_token_id,
    scope,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, token_family_id, token_hash, client_id, user_id, access_token_id, previous_token_id, scope, expires_at, is_revoked, revoked_at, revoke_reason, used_at, created_at
`

type CreateRefreshTokenParams struct {
	TokenHash       string
	TokenFamilyID   uuid.UUID
	ClientID        uuid.UUID
	UserID          uuid.UUID
	AccessTokenID   uuid.UUID
	PreviousTokenID *uuid.UUID
	Scope           string
	ExpiresAt       time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.TokenHash,
		arg.TokenFamilyID,
		arg.ClientID,
		arg.UserID,
		arg.AccessTokenID,
		arg.PreviousTokenID,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenFamilyID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.AccessTokenID,
		&i.PreviousTokenID,
		&i.Scope,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, token_family_id, token_hash, client_id, user_id, access_token_id, previous_token_id, scope, expires_at, is_revoked, revoked_at, revoke_reason, used_at, created_at FROM refresh_tokens
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenFamilyID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.AccessTokenID,
		&i.PreviousTokenID,
		&i.Scope,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByID = `-- name: GetRefreshTokenByID :one
SELECT id, token_family_id, token_hash, client_id, user_id, access_token_id, previous_token_id, scope, expires_at, is_revoked, revoked_at, revoke_reason, used_at, created_at FROM refresh_tokens
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRefreshTokenByID(ctx context.Context, id uuid.UUID) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByID, id)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenFamilyID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.AccessTokenID,
		&i.PreviousTokenID,
		&i.Scope,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listRefreshTokensByUser = `-- name: ListRefreshTokensByUser :many
SELECT id, token_family_id, token_hash, client_id, user_id, access_token_id, previous_token_id, scope, expires_at, is_revoked, revoked_at, revoke_reason, used_at, created_at FROM refresh_tokens
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRefreshTokensByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListRefreshTokensByUser(ctx context.Context, arg ListRefreshTokensByUserParams) ([]RefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokensByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RefreshToken
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.TokenFamilyID,
			&i.TokenHash,
			&i.ClientID,
			&i.UserID,
			&i.AccessTokenID,
			&i.PreviousTokenID,
			&i.Scope,
			&i.ExpiresAt,
			&i.IsRevoked,
			&i.RevokedAt,
			&i.RevokeReason,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens
SET used_at = now(), is_revoked = true, revoke_reason = 'used'
WHERE id = $1
`

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, id)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET is_revoked = true, revoked_at = now(), revoke_reason = $2
WHERE id = $1
`

type RevokeRefreshTokenParams struct {
	ID           uuid.UUID
	RevokeReason *string
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.RevokeReason)
	return err
}

const revokeRefreshTokenFamily = `-- name: RevokeRefreshTokenFamily :exec
UPDATE refresh_tokens
SET is_revoked = true, revoked_at = now(), revoke_reason = $2
WHERE token_family_id = $1
`

type RevokeRefreshTokenFamilyParams struct {
	TokenFamilyID uuid.UUID
	RevokeReason  *string
}

func (q *Queries) RevokeRefreshTokenFamily(ctx context.Context, arg RevokeRefreshTokenFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenFamily, arg.TokenFamilyID, arg.RevokeReason)
	return err
}

const revokeRefreshTokensByUser = `-- name: RevokeRefreshTokensByUser :exec
UPDATE refresh_tokens
SET is_revoked = true, revoked_at = now(), revoke_reason = $2
WHERE user_id = $1 AND is_revoked = false
`

type RevokeRefreshTokensByUserParams struct {
	UserID       uuid.UUID
	RevokeReason *string
}

func (q *Queries) RevokeRefreshTokensByUser(ctx context.Context, arg RevokeRefreshTokensByUserParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokensByUser, arg.UserID, arg.RevokeReason)
	return err
}
