// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"time"

	models "github.com/SamuelWang/goauth-server/internal/models"
	"github.com/google/uuid"
)

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT
  COUNT(*)
FROM
  users
WHERE
  is_admin = true
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT
  COUNT(*)
FROM
  users
WHERE
  ($1::boolean IS NULL OR is_active = $1)
  AND ($2::boolean IS NULL OR is_admin = $2)
`

type CountUsersParams struct {
	Column1 bool
	Column2 bool
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (
    email,
    email_verified,
    first_name,
    last_name,
    provider,
    provider_id,
    provider_data,
    locale,
    last_login_at
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
`

type CreateUserParams struct {
	Email         string
	EmailVerified bool
	FirstName     *string
	LastName      *string
	Provider      *string
	ProviderID    *string
	ProviderData  *models.OAuthProviderData
	Locale        string
	LastLoginAt   time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.EmailVerified,
		arg.FirstName,
		arg.LastName,
		arg.Provider,
		arg.ProviderID,
		arg.ProviderData,
		arg.Locale,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
FROM
  users
WHERE
  email = $1
LIMIT
  1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByEmailForAuth = `-- name: GetUserByEmailForAuth :one
SELECT
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
FROM
  users
WHERE
  email = $1
LIMIT
  1
`

func (q *Queries) GetUserByEmailForAuth(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailForAuth, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
FROM
  users
WHERE
  id = $1
LIMIT
  1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one
SELECT
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
FROM
  users
WHERE
  provider = $1
  AND provider_id = $2
LIMIT
  1
`

type GetUserByProviderIDParams struct {
	Provider   *string
	ProviderID *string
}

func (q *Queries) GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderID, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const getUsersByAdmin = `-- name: GetUsersByAdmin :many
SELECT
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
FROM
  users
WHERE
  is_admin = $1
ORDER BY
  created_at DESC
`

func (q *Queries) GetUsersByAdmin(ctx context.Context, isAdmin *bool) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersByAdmin, isAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.FirstName,
			&i.LastName,
			&i.IsActive,
			&i.Locale,
			&i.Provider,
			&i.ProviderID,
			&i.ProviderData,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAdmin,
			&i.PasswordHash,
			&i.ForcePasswordChange,
			&i.FailedLoginAttempts,
			&i.LastFailedLoginAt,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :one
UPDATE users
SET
  failed_login_attempts = failed_login_attempts + 1,
  last_failed_login_at = now(),
  updated_at = now()
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
`

func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, incrementFailedLoginAttempts, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
FROM
  users
WHERE
  ($1::boolean IS NULL OR is_active = $1)
  AND ($2::boolean IS NULL OR is_admin = $2)
ORDER BY
  created_at DESC
LIMIT
  $3
OFFSET
  $4
`

type ListUsersParams struct {
	Column1 bool
	Column2 bool
	Limit   int32
	Offset  int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.FirstName,
			&i.LastName,
			&i.IsActive,
			&i.Locale,
			&i.Provider,
			&i.ProviderID,
			&i.ProviderData,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsAdmin,
			&i.PasswordHash,
			&i.ForcePasswordChange,
			&i.FailedLoginAttempts,
			&i.LastFailedLoginAt,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserAccount = `-- name: LockUserAccount :one
UPDATE users
SET
  locked_until = $2,
  updated_at = now()
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
`

type LockUserAccountParams struct {
	ID          uuid.UUID
	LockedUntil time.Time
}

func (q *Queries) LockUserAccount(ctx context.Context, arg LockUserAccountParams) (User, error) {
	row := q.db.QueryRow(ctx, lockUserAccount, arg.ID, arg.LockedUntil)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const resetLoginAttempts = `-- name: ResetLoginAttempts :one
UPDATE users
SET
  failed_login_attempts = 0,
  last_failed_login_at = NULL,
  locked_until = NULL,
  updated_at = now()
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
`

func (q *Queries) ResetLoginAttempts(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, resetLoginAttempts, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const setForcePasswordChange = `-- name: SetForcePasswordChange :one
UPDATE users
SET
  force_password_change = $2,
  updated_at = now()
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
`

type SetForcePasswordChangeParams struct {
	ID                  uuid.UUID
	ForcePasswordChange bool
}

func (q *Queries) SetForcePasswordChange(ctx context.Context, arg SetForcePasswordChangeParams) (User, error) {
	row := q.db.QueryRow(ctx, setForcePasswordChange, arg.ID, arg.ForcePasswordChange)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const unlockUserAccount = `-- name: UnlockUserAccount :one
UPDATE users
SET
  locked_until = NULL,
  updated_at = now()
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
`

func (q *Queries) UnlockUserAccount(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, unlockUserAccount, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :one
UPDATE users
SET
  provider_data = $2,
  last_login_at = $3
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
`

type UpdateLastLoginParams struct {
	ID           uuid.UUID
	ProviderData *models.OAuthProviderData
	LastLoginAt  time.Time
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, updateLastLogin, arg.ID, arg.ProviderData, arg.LastLoginAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :one
UPDATE users
SET
  password_hash = $2,
  updated_at = now()
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
`

type UpdatePasswordHashParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  email = $2,
  email_verified = $3,
  first_name = $4,
  last_name = $5,
  locale = $6
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
`

type UpdateUserParams struct {
	ID            uuid.UUID
	Email         string
	EmailVerified bool
	FirstName     *string
	LastName      *string
	Locale        string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.EmailVerified,
		arg.FirstName,
		arg.LastName,
		arg.Locale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}

const updateUserActiveStatus = `-- name: UpdateUserActiveStatus :one
UPDATE users
SET
  is_active = $2,
  updated_at = now()
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin, password_hash, force_password_change, failed_login_attempts, last_failed_login_at, locked_until
`

type UpdateUserActiveStatusParams struct {
	ID       uuid.UUID
	IsActive bool
}

func (q *Queries) UpdateUserActiveStatus(ctx context.Context, arg UpdateUserActiveStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserActiveStatus, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
		&i.PasswordHash,
		&i.ForcePasswordChange,
		&i.FailedLoginAttempts,
		&i.LastFailedLoginAt,
		&i.LockedUntil,
	)
	return i, err
}
