// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"
	"time"

	models "github.com/SamuelWang/goauth-server/internal/models"
	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
  users (
    email,
    email_verified,
    first_name,
    last_name,
    provider,
    provider_id,
    provider_data,
    locale,
    last_login_at
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin
`

type CreateUserParams struct {
	Email         string
	EmailVerified bool
	FirstName     *string
	LastName      *string
	Provider      *string
	ProviderID    *string
	ProviderData  *models.OAuthProviderData
	Locale        string
	LastLoginAt   time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.EmailVerified,
		arg.FirstName,
		arg.LastName,
		arg.Provider,
		arg.ProviderID,
		arg.ProviderData,
		arg.Locale,
		arg.LastLoginAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin
FROM
  users
WHERE
  email = $1
LIMIT
  1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin
FROM
  users
WHERE
  id = $1
LIMIT
  1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const getUserByProviderID = `-- name: GetUserByProviderID :one
SELECT
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin
FROM
  users
WHERE
  provider = $1
  AND provider_id = $2
LIMIT
  1
`

type GetUserByProviderIDParams struct {
	Provider   *string
	ProviderID *string
}

func (q *Queries) GetUserByProviderID(ctx context.Context, arg GetUserByProviderIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByProviderID, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :one
UPDATE users
SET
  provider_data = $2,
  last_login_at = $3
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin
`

type UpdateLastLoginParams struct {
	ID           uuid.UUID
	ProviderData *models.OAuthProviderData
	LastLoginAt  time.Time
}

func (q *Queries) UpdateLastLogin(ctx context.Context, arg UpdateLastLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, updateLastLogin, arg.ID, arg.ProviderData, arg.LastLoginAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  email = $2,
  email_verified = $3,
  first_name = $4,
  last_name = $5,
  locale = $6
WHERE
  id = $1
RETURNING
  id, email, email_verified, first_name, last_name, is_active, locale, provider, provider_id, provider_data, last_login_at, created_at, updated_at, is_admin
`

type UpdateUserParams struct {
	ID            uuid.UUID
	Email         string
	EmailVerified bool
	FirstName     *string
	LastName      *string
	Locale        string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.EmailVerified,
		arg.FirstName,
		arg.LastName,
		arg.Locale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirstName,
		&i.LastName,
		&i.IsActive,
		&i.Locale,
		&i.Provider,
		&i.ProviderID,
		&i.ProviderData,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsAdmin,
	)
	return i, err
}
